### PR TITLE
Enable word-wrap for pre blocks

### PR DESCRIPTION
**Pull request by Mygod**
It's probably a good idea to wrap this into an option.

### CODE REVIEW

**Comment by Mygod** [comment]
Also the version code seems to be inconsistent.

**Comment by pixelb** [comment]
I guess that's a sensible default, and has enough browser support
thanks

**Comment by Mygod** [comment]
That makes sense because most TTY do wraps.

**Comment by pixelb** [comment]
Pushed at commit dce76891

**Pull request closed without merging**
